# Generated by Django 5.0.1 on 2024-01-27 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveIntegerField()),
                ('nome_mes', models.CharField(max_length=20)),
                ('quinzena', models.PositiveIntegerField()),
                ('semana', models.PositiveIntegerField()),
                ('dia', models.PositiveIntegerField()),
                ('horas_trabalhadas', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pessoa')),
            ],
            options={
                'unique_together': {('pessoa', 'mes', 'quinzena', 'semana', 'dia')},
            },
        ),
    ]
