# Generated by Django 5.0.1 on 2024-01-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_registrohoras'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificacao',
            name='horas_trabalhadas_horas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verificacao',
            name='horas_trabalhadas_minutos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
