# Generated by Django 5.0.1 on 2024-01-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_verificacao_duracao_trabalho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificacao',
            name='entrada_correta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verificacao',
            name='saida_correta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
