# Generated by Django 5.0.1 on 2024-01-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_verificacao_entrada_correta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificacao',
            name='duracao_trabalho',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
