# Generated by Django 5.0.1 on 2024-01-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_verificacao_entrada_correta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificacao',
            name='horario_entrada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verificacao',
            name='horario_saida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
