# Generated by Django 5.0.1 on 2024-01-29 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_verificacao_duracao_trabalho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificacao',
            name='duracao_trabalho',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
