# Generated by Django 5.0.1 on 2024-01-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_verificacao_duracao_trabalho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificacao',
            name='duracao_trabalho',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
